on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-composite-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello World no shell
        uses: ./.github/actions/composite
